config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  get 'test' => 'pages#test'
  get 'body_measurement' => 'bodies#new'
  get 'bmi_calculator' => 'pages#bmi_calculator'
  get 'warriors_gallery' => 'pages#warriors_gallery'
  get 'body_measurement_public' => 'pages#body_measurement_public'
  get 'about' => 'pages#about'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'mypage', to: 'about#me', as: 'mypage'
  get 'mytable', to: 'about#my_table', as: 'mytable'
  get 'mysetting', to: 'about#setting', as: 'mysetting'
  get 'edit', to: 'users#edit', as: 'edit'
  post 'edit', to: 'users#update'
  get 'index', to: 'users#index', as: 'index'
  get 'update', to: 'bodies#new', as: 'update'
  get 'bodyindex', to: 'bodies#index', as: 'bodyindex'

resources :users
resources :sessions
resources :bodies
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def me
    @logged_in_user = User.find_by :id => session[:user_id]
    # @logged_in_user = @current_user.id
    @bodies = Body.all
    # @line_graph_data = Body.where(:user_id => current_user.id).group(:id).sum(:weight)
    # @line_graph_data1 = Body.where(:user_id => current_user.id).group_by_day(:date, format: "%e").average(:weight)
    #  puts "===================================="
    #     puts @line_graph_data1.inspect
    #     puts "==================================="
    @result = {}
    Body.where(:user_id => current_user.id).each do |body|
      @result[body.date.day] = body.weight
    end
        #  puts "===================================="
        # puts @result.inspect
        # puts "==================================="
    
  end

  def my_table
    @bodies = Body.where(:user_id => session[:user_id]) 
        puts "===================================="
        puts @bodies.inspect
        puts "==================================="
    @logged_in_user = User.find_by :id => session[:user_id]
    @title = 'see how far you have come.';
   
    # @tr = Body.find(params[:id])
    #  puts "===================================="
    #     puts @tr.inspect
    #     puts "==================================="
    # @bmi = @tr.weight/(@tr.height^2)
  end



  def setting
    @logged_in_user = User.find_by :id => session[:user_id]
    # @line_graph_data = Body.where(:user_id => current_user.id).group(:id).sum(:weight)
    # @bmi = @logged_in_user.initial_weight/@logged_in_user.height/@logged_in_user.height
  end

  def edit
    @logged_in_user = User.find_by :id => session[:user_id]
  end

   def create
        form_params = get_create_user_form_params()
        @user = User.find_by :id => session[:user_id] 
        @user.save
            redirect_to mytable_url, notice: "Thank you for signing up!"
    end
    private
    def get_create_user_form_params
        params.require(:update_body_info).permit(:weight)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/me.html.erb
<div class="d-flex flex-row banner6"><b>Welcome back, <%= @logged_in_user.name %> from <%= @logged_in_user.city %> ! </b></div>

<hr>
<%# <%= line_chart @line_graph_data %>
<%# <%= line_chart @line_graph_data1, xtitle: "Date", ytitle: "Weight"%> %>
<%= line_chart @result %>

app/views/about/my_table.html.erb
<div class="d-flex flex-row banner7"><b>Hi, <%= @logged_in_user.name %>, <%= @title %></div>

<h1>Your Records</h1>
<table class="table table-hover">
    <tr>
    <th scope="col">Id</th>
    <th scope="col">Weight</th>
    <th scope="col">Height</th>

    <th scope="col">Created at</th>
    <th scope="col">Record time</th>
    <th scope="col"></th>
    </tr>
    <% @bodies.each do |body| %>
    <tr>
    <td><%= body.id %></td>
    <td><%= body.weight %></td>
    <td><%= body.height %></td>

    <td><%= localize(body.created_at + 39600, :format => :long) %></td>
    <td><%= localize(body.date, :format => "%d %b %Y") %></td>
    <td><%= link_to 'Delete', body_path(body), method: 'delete' %></td>

    </tr>
    <% end %>
</table>

app/views/about/setting.html.erb
<div class="d-flex flex-row banner8"><b>Hi, <%= @logged_in_user.name %>! You are the #<%= @logged_in_user.id %> member using our app.</div>
<h1>Your details</h1>


<p><b>Email:</b> <%= @logged_in_user.email %></p>
<p><b>City:</b> <%= @logged_in_user.city %></p>
<p><b>Gender:</b> <%= @logged_in_user.gender%></p>
<p><b>Created at:</b> <%= localize(@logged_in_user.created_at + 39600, :format => :long) %></p>
<a href="/edit" class="btn btn-primary">Edit</a>

<%# <hr>
<%= line_chart @line_graph_data%>