config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  get 'test' => 'pages#test'
  get 'body_measurement' => 'bodies#new'
  get 'bmi_calculator' => 'pages#bmi_calculator'
  get 'warriors_gallery' => 'pages#warriors_gallery'
  get 'body_measurement_public' => 'pages#body_measurement_public'
  get 'about' => 'pages#about'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'mypage', to: 'about#me', as: 'mypage'
  get 'mytable', to: 'about#my_table', as: 'mytable'
  get 'mysetting', to: 'about#setting', as: 'mysetting'
  get 'edit', to: 'users#edit', as: 'edit'
  post 'edit', to: 'users#update'
  get 'index', to: 'users#index', as: 'index'
  get 'update', to: 'bodies#new', as: 'update'
  get 'bodyindex', to: 'bodies#index', as: 'bodyindex'

resources :users
resources :sessions
resources :bodies
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthTracking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
   
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    
  <a class="navbar-brand" href="/about">HealthTracking</a>
  
  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>

  <%# <div class="collapse navbar-collapse" id="navbarNavDropdown"> %>
  
    <ul class="navbar-nav">
      <li class="nav-item, navigation active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
  
      <li class="nav-item, navigation">
        <a class="nav-link" href="/body_measurement_public">Body Measurement</a>
      </li>
      <li class="nav-item, navigation">
        <a class="nav-link" href="/bmi_calculator">BMI Calculator</a>
      </li>
      <li class="nav-item, navigation">
        <a class="nav-link" href="/warriors_gallery">Warriors' Gallery</a>
      </li>
      <li class="nav-item, login">
      <a class="nav-link">
        <% if current_user %>
        Logged in as <%= current_user.email %>
        <b><%= link_to "My Dashboard", mypage_path %></b>
        <br />
        <b><%= link_to "My Table", mytable_path %></b>
        <br />
        <b><%= link_to "Profile", mysetting_path %></b>
        <br />
        <b><%= link_to "Log Out", logout_path %></b>
        <% else %>
        <b><%= link_to "Sign Up", signup_path %></b> or
        <b><%= link_to "Log In", login_path %></b>
        <% end %>
        </a>
      </li>
    </ul>
  <%# </div> %>
</nav>

<!--<div class="logo">
<%= image_tag('logos/logo.jpeg', width: '300px') %>
</div>-->
<div class="maincontent">
    <%= yield %>
</div>
  <!-- bottom -->
  <div class="d-flex bottomArea p-3 mt-5">
  <div class="w-60">
  <%= image_tag('logos/logo.jpeg', :class => 'img-fluid h-25') %> 
  <h5>About Us</h5>
         <section class="media">
    <span style="font-size: 36px; color: black;">
      <span class="facebook" title="facebook"><i class="fab fa-facebook-f"></i></span>
    <span class="twitter" title="twitter"><i class="fab fa-twitter"></i></span>
    <span class="youtube" title="youtube"><i class="fab fa-youtube"></i></span>
    <span class="pinterest" title="pinterest"><i class="fab fa-pinterest"></i></span>
    </span>
    </section>
  <section class="copyright">
      <h5>&copy;2019 General Assembly Lab</h5>
    </section>
  </div>
  <div class="d-flex flex-column mt-3 ml-5 ">
      <h5>Contact Us</h5>
 
      <div>123 Sydney Road</div>
      <div>555-55555</div>
      <div><%= mail_to "chenhe.elec@gmail.com", cc: "hannaliu59@hotmail.com", subject: "This is a test email." do %>
          <strong>Email me:</strong> <span>chenhe.elec@gmail.com</span>
          <% end %>
      </div>
  </div>
</div>
  </body>
  
</html>